# Generated by Django 2.2.1 on 2019-10-06 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20191005_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='user_account_id',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='category_id',
        ),
    ]
